'use strict';

const PDFDocument = require('pdfkit');
const dayjs = require('dayjs');
const { getDefectById } = require('./defects');

// PUBLIC_INTERFACE
async function generateDefectAuditPdf({ defectId, actor }) {
  /**
   * Generate a PDF audit report for a defect, returning a Buffer.
   */
  const defect = await getDefectById(defectId);
  if (!defect) return null;

  const doc = new PDFDocument({ size: 'A4', margin: 50 });

  const chunks = [];
  doc.on('data', (d) => chunks.push(d));

  const title = `Defect Audit Report - ${defect.id}`;
  doc.fontSize(18).text(title, { align: 'left' });
  doc.moveDown(0.5);
  doc.fontSize(10).fillColor('#666666').text(`Generated: ${dayjs().format('YYYY-MM-DD HH:mm')}`);
  doc.text(`Generated by: ${actor.email} (${actor.role})`);
  doc.moveDown();

  doc.fillColor('#000000').fontSize(12).text('Defect Summary', { underline: true });
  doc.moveDown(0.25);
  doc.fontSize(11);
  doc.text(`Title: ${defect.title}`);
  doc.text(`Type: ${defect.defectType || '-'}`);
  doc.text(`Severity: ${defect.severity}`);
  doc.text(`Status: ${defect.status}`);
  doc.text(`Station: ${defect.station || '-'}`);
  doc.text(`Part Number: ${defect.partNumber || '-'}`);
  doc.text(`Lot Number: ${defect.lotNumber || '-'}`);
  doc.text(`Quantity Affected: ${defect.quantityAffected || 0}`);
  doc.text(`Due Date: ${defect.dueDate || '-'}`);
  doc.text(`Created At: ${defect.createdAt || '-'}`);
  doc.text(`Updated At: ${defect.updatedAt || '-'}`);
  doc.moveDown();

  doc.fontSize(12).text('Description', { underline: true });
  doc.moveDown(0.25);
  doc.fontSize(11).text(defect.description || '-', { width: 500 });
  doc.moveDown();

  doc.fontSize(12).text('Root Cause Analysis (5-Why)', { underline: true });
  doc.moveDown(0.25);
  if (!defect.rca) {
    doc.fontSize(11).text('No RCA submitted.');
  } else {
    const rca = defect.rca;
    doc.fontSize(11).text(`Method: ${rca.method}`);
    if (Array.isArray(rca.whyChain) && rca.whyChain.length > 0) {
      doc.moveDown(0.25);
      rca.whyChain.forEach((w, idx) => {
        doc.text(`${idx + 1}. ${w}`, { indent: 10 });
      });
    }
    doc.moveDown(0.25);
    doc.text(`Root Cause: ${rca.rootCause || '-'}`);
    doc.text(`Containment: ${rca.containment || '-'}`);
    doc.text(`Submitted At: ${rca.submittedAt || '-'}`);
  }
  doc.moveDown();

  doc.fontSize(12).text('Corrective Actions', { underline: true });
  doc.moveDown(0.25);
  if (!defect.correctiveActions || defect.correctiveActions.length === 0) {
    doc.fontSize(11).text('No corrective actions.');
  } else {
    defect.correctiveActions.forEach((a, idx) => {
      doc.fontSize(11).text(`${idx + 1}. ${a.title} [${a.status}]`);
      doc.fontSize(10).fillColor('#444444');
      doc.text(`Owner: ${a.owner || '-'}  Due: ${a.dueDate || '-'}  AssignedTo: ${a.assignedToUserId || '-'}`, { indent: 10 });
      if (a.notes) doc.text(`Notes: ${a.notes}`, { indent: 10 });
      doc.fillColor('#000000');
      doc.moveDown(0.25);
    });
  }
  doc.moveDown();

  doc.fontSize(12).text('Attachments', { underline: true });
  doc.moveDown(0.25);
  if (!defect.attachments || defect.attachments.length === 0) {
    doc.fontSize(11).text('No attachments.');
  } else {
    defect.attachments.forEach((att, idx) => {
      doc.fontSize(10).text(`${idx + 1}. ${att.filename} (${att.mimeType}, ${att.size} bytes)`);
      doc.fillColor('#1f6feb').text(att.url, { link: att.url, underline: true });
      doc.fillColor('#000000');
      doc.moveDown(0.2);
    });
  }

  doc.end();

  const buffer = await new Promise((resolve) => {
    doc.on('end', () => resolve(Buffer.concat(chunks)));
  });

  return buffer;
}

module.exports = {
  generateDefectAuditPdf,
};
